// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GlobalStats struct {
	FoodEaten int32 `json:"foodEaten"`
	Kills     int32 `json:"kills"`
}

type Player struct {
	FoodEaten int32 `json:"foodEaten"`
	Deaths    int32 `json:"deaths"`
	Kills     int32 `json:"kills"`
}

type Query struct {
}
