// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GlobalStats struct {
	PlayerFoodEaten int32 `json:"playerFoodEaten"`
	PlayerKills     int32 `json:"playerKills"`
	PlayerDeaths    int32 `json:"playerDeaths"`
	BotFoodEaten    int32 `json:"botFoodEaten"`
	BotKills        int32 `json:"botKills"`
	BotDeaths       int32 `json:"botDeaths"`
}

type Player struct {
	FoodEaten int32 `json:"foodEaten"`
	Deaths    int32 `json:"deaths"`
	Kills     int32 `json:"kills"`
}

type Query struct {
}
